import numpy as np

TYPE_BOOL = 'BOOLEAN'
TYPE_DATE = 'DATE'
TYPE_GEO = 'GEOMETRY'
TYPE_NUM = 'NUMERIC'
TYPE_STR = 'STRING'

TYPE_UNSUPPORTED = 'UNSUPPORTED'

TYPE_CONST = 'CONSTANT'
TYPE_EMPTY = 'EMPTY'
TYPE_UNIQUE = 'UNIQUE'

NULLS = [None, np.nan, 'null', '']
SHAPE_BOUNDS = [1, np.nan]
